spring:
#jdbc driver Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/online_shopping_application?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
 #       dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true    
 #smtp configuration
  mail:
   host: smtp.gmail.com
   port: 587 
   username: ${mail.username} 
   password: ${mail.password}
   properties:
    mail:
     smtp:
      starttls:
        enable: true
        required: true       
          
#this is values of the cookies and jwt properties for the accessToke & refreshToken 
#application configuration file     
application:
   jwt:
      secret: ${jwt.secret}
      access_expiry_seconds: 3600
      refresh_expiry_seconds: 1296000
   cookie:
      domain: localhost
      same_site: Lax
      secure: false
                
        
        
        
        
        
        
        
        
        
        
        